environment:
  matrix:
  - PYTHON: "C:\\Python36"
  - PYTHON: "C:\\Python36-x64"
  - PYTHON: "C:\\Python35"
  - PYTHON: "C:\\Python35-x64"
  
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip3.exe install cx_Freeze --upgrade"

build: off

before_test:
  - "setup.py build"

test_script:
  - "test.py"

artifacts:
  - path: dist\*